-- books.polascin.net: catalog update, 2 September 2026
-- Source: Amazon product pages verified on 2026-09-02 (author Walter Kyo Csoelle).
-- 1) Fixes to four existing records (format label in title, publication year, description).
-- 2) Six new print editions (paperback + hardcover of Vital Algorithm, BLOOD EQUITY, Pulse Of The Body).
-- Mirrors data/books.json at the same commit. Rows are matched by isbn/ASIN, not by id, so it is safe
-- even if production ids differ from the JSON seed. Inserts are skipped when the ISBN already exists.

START TRANSACTION;

-- 1) fixes
UPDATE books SET title = 'Vital Algorithm: A Novel of Code and Conscience (Kindle Edition, 2nd ed.)', year = 2026, description = 'Kindle Edition, 2nd edition - January 13, 2026 by Walter Kyo Csoelle (ASIN B0GGJXHQDH, 410 pages). If an algorithm had to choose between saving a wealthy CEO or a beloved kindergarten teacher, how would it decide? Dr. Jana Bravcova returns to Bratislava to join MedCore, where VITAL-7 and the Social Utility Score price patients by economic value. As she uncovers a so-called glitch that was actually murder, she must choose between compliance and stopping the system. Written by Dr. Lubomir Polascin, this second edition adds a Developer\'s Cut appendix, an updated AI chapter for 2026, a new afterword (\'Leaving the Factory\'), and a reading group guide.' WHERE isbn = 'B0GGJXHQDH';
UPDATE books SET title = 'The Vital Algorithm: A Novel of Code and Conscience (Kindle Edition, 1st ed.)', year = 2025, description = 'Kindle Edition, 1st edition - November 29, 2025 by Walter Kyo Csoelle (ASIN B0FFGG4K4D, 358 pages). If an algorithm had to choose between saving a wealthy CEO or a beloved kindergarten teacher, how would it decide? Dr. Jana Bravcová returns to Bratislava to join MedCore and confronts VITAL-7, where the Social Utility Score prices human life. As she uncovers a so-called glitch that was actually murder, she must decide whether to comply or crash the system. Original first edition of the novel, written by Dr. Ľubomír Polaščín; superseded by the expanded second edition (January 2026), which is also available in paperback and hardcover. Perfect for readers of Black Mirror and Robin Cook.' WHERE isbn = 'B0FFGG4K4D';
UPDATE books SET title = 'BLOOD EQUITY: Some Cures Are Deadlier Than Disease (Kindle Edition)', year = 2025, description = 'Kindle Edition - November 23, 2025 by Walter Kyo Csoelle (ASIN B0G3MLQ1PN, 195 pages). In the post-socialist Republic of Carpathia, Severograd faces predatory healthcare corporatization as VitaCorp expands and targets independent nephrologist Dr. Andrej Varga. Refusing to sell his clinic, Varga uncovers lethal cost-cutting practices including involuntary discharge of unprofitable patients, reuse of single-use dialyzers, and shortened dialysis sessions. With whistleblower nurse Lena, he gathers evidence while enduring bureaucratic sabotage, media attacks, and physical intimidation. The conflict culminates at the EU Healthcare Summit, where Varga exposes falsified records, contaminated filters, and systemic corruption tied to corporate and political actors. Although key figures fall, the novel ends with a realistic warning that the deeper system remains and ethical medicine must be defended continuously.' WHERE isbn = 'B0G3MLQ1PN';
UPDATE books SET title = 'Pulse Of The Body: A Novel of Medicine, Humanity, and the Edge of Life (Kindle Edition)', year = 2025, description = 'Kindle Edition - November 18, 2025 by Walter Kyo Csoelle (ASIN B0DHQY58C8, 214 pages). The novel follows Thomas Shimur, a former biology teacher with terminal kidney failure, as he enters a nephrology ward and confronts fear, grief, identity loss, and acceptance. Dr. Lea Mountchain, burdened by unresolved clinical trauma, and Prof. Victor Kraal, a visionary but ethically conflicted renal surgeon, become central to his journey. Across dialysis rooms, surgical theaters, ICU corridors, and family confrontations, the story explores dependence, dignity, informed choice, and the limits of intervention. Thomas undergoes radical surgery, survives into a fragile recovery period, rebuilds damaged relationships, and reaches a deeper acceptance of mortality. His eventual death transforms the ward: Lea embraces a more humane, narrative-centered model of care, while Kraal redefines success beyond technical triumph. Pulse of the Body portrays nephrology as a microcosm of human life where technology, ethics, love, guilt, hope, and grief intersect.' WHERE isbn = 'B0DHQY58C8';

-- 2) new print editions
INSERT INTO books (title, author, year, isbn, description, cover_image, url, web_url, language, category)
  SELECT 'Vital Algorithm: A Novel of Code and Conscience (Paperback)', 'Walter Kyo Csoelle', 2026, '9798243848893', 'Paperback - January 13, 2026 by Walter Kyo Csoelle. Independently published, 415 pages, ISBN-13 979-8243848893 (ASIN B0GGQGWGQY). If an algorithm had to choose between saving a wealthy CEO or a beloved kindergarten teacher, how would it decide? Dr. Jana Bravcová returns to Bratislava to join MedCore and confronts VITAL-7, where the Social Utility Score prices human life. As she uncovers a so-called glitch that was actually murder, she must decide whether to comply or crash the system. Written by Dr. Ľubomír Polaščín, this second edition includes the Developer\'s Cut appendix, an updated AI chapter (2026), a new afterword (Leaving the Factory), and a reading group guide. Perfect for readers of Black Mirror and Robin Cook.', 'https://m.media-amazon.com/images/I/71UQ-KDLqqL._SY466_.jpg', 'https://www.amazon.com/dp/B0GGQGWGQY', 'https://www.amazon.com/stores/author/B0G2TCCJZZ', 'English', 'Medical Thriller'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM books WHERE isbn = '9798243848893');
INSERT INTO books (title, author, year, isbn, description, cover_image, url, web_url, language, category)
  SELECT 'Vital Algorithm: A Novel of Code and Conscience (Hardcover)', 'Walter Kyo Csoelle', 2026, '9798243857475', 'Hardcover - January 13, 2026 by Walter Kyo Csoelle. Independently published, 415 pages, ISBN-13 979-8243857475 (ASIN B0GGQL6LTT). If an algorithm had to choose between saving a wealthy CEO or a beloved kindergarten teacher, how would it decide? Dr. Jana Bravcová returns to Bratislava to join MedCore and confronts VITAL-7, where the Social Utility Score prices human life. As she uncovers a so-called glitch that was actually murder, she must decide whether to comply or crash the system. Written by Dr. Ľubomír Polaščín, this second edition includes the Developer\'s Cut appendix, an updated AI chapter (2026), a new afterword (Leaving the Factory), and a reading group guide. Perfect for readers of Black Mirror and Robin Cook.', 'https://m.media-amazon.com/images/I/61gzTjIS8DL._SY466_.jpg', 'https://www.amazon.com/dp/B0GGQL6LTT', 'https://www.amazon.com/stores/author/B0G2TCCJZZ', 'English', 'Medical Thriller'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM books WHERE isbn = '9798243857475');
INSERT INTO books (title, author, year, isbn, description, cover_image, url, web_url, language, category)
  SELECT 'BLOOD EQUITY: Some Cures Are Deadlier Than Disease (Paperback)', 'Walter Kyo Csoelle', 2025, '9798275766110', 'Paperback - November 23, 2025 by Walter Kyo Csoelle. Independently published, 193 pages, ISBN-13 979-8275766110 (ASIN B0G3PZ47C1). In the post-socialist Republic of Carpathia, Severograd faces predatory healthcare corporatization as VitaCorp expands and targets independent nephrologist Dr. Andrej Varga. Refusing to sell his clinic, Varga uncovers lethal cost-cutting practices including involuntary discharge of unprofitable patients, reuse of single-use dialyzers, and shortened dialysis sessions. With whistleblower nurse Lena, he gathers evidence while enduring bureaucratic sabotage, media attacks, and physical intimidation. The conflict culminates at the EU Healthcare Summit, where Varga exposes falsified records, contaminated filters, and systemic corruption tied to corporate and political actors.', 'https://m.media-amazon.com/images/I/71iDiB6VC3L._SY466_.jpg', 'https://www.amazon.com/dp/B0G3PZ47C1', 'https://www.amazon.com/stores/author/B0G2TCCJZZ', 'English', 'Medical Thriller'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM books WHERE isbn = '9798275766110');
INSERT INTO books (title, author, year, isbn, description, cover_image, url, web_url, language, category)
  SELECT 'BLOOD EQUITY: Some Cures Are Deadlier Than Disease (Hardcover)', 'Walter Kyo Csoelle', 2025, '9798275768503', 'Hardcover - November 23, 2025 by Walter Kyo Csoelle. Independently published, 193 pages, ISBN-13 979-8275768503 (ASIN B0G3NXZCNF). In the post-socialist Republic of Carpathia, Severograd faces predatory healthcare corporatization as VitaCorp expands and targets independent nephrologist Dr. Andrej Varga. Refusing to sell his clinic, Varga uncovers lethal cost-cutting practices including involuntary discharge of unprofitable patients, reuse of single-use dialyzers, and shortened dialysis sessions. With whistleblower nurse Lena, he gathers evidence while enduring bureaucratic sabotage, media attacks, and physical intimidation. The conflict culminates at the EU Healthcare Summit, where Varga exposes falsified records, contaminated filters, and systemic corruption tied to corporate and political actors.', 'https://m.media-amazon.com/images/I/612ccpp5XPL._SY466_.jpg', 'https://www.amazon.com/dp/B0G3NXZCNF', 'https://www.amazon.com/stores/author/B0G2TCCJZZ', 'English', 'Medical Thriller'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM books WHERE isbn = '9798275768503');
INSERT INTO books (title, author, year, isbn, description, cover_image, url, web_url, language, category)
  SELECT 'Pulse Of The Body: A Novel of Medicine, Humanity, and the Edge of Life (Paperback)', 'Walter Kyo Csoelle', 2025, '9798275086690', 'Paperback - November 18, 2025 by Walter Kyo Csoelle. Independently published, 212 pages, ISBN-13 979-8275086690 (ASIN B0G2WW1CKG). The novel follows Thomas Shimur, a former biology teacher with terminal kidney failure, as he enters a nephrology ward and confronts fear, grief, identity loss, and acceptance. Dr. Lea Mountchain, burdened by unresolved clinical trauma, and Prof. Victor Kraal, a visionary but ethically conflicted renal surgeon, become central to his journey. Across dialysis rooms, surgical theaters, ICU corridors, and family confrontations, the story explores dependence, dignity, informed choice, and the limits of intervention. Pulse of the Body portrays nephrology as a microcosm of human life where technology, ethics, love, guilt, hope, and grief intersect.', 'https://m.media-amazon.com/images/I/61rXYWPELLL._SY466_.jpg', 'https://www.amazon.com/dp/B0G2WW1CKG', 'https://www.amazon.com/stores/author/B0G2TCCJZZ', 'English', 'Medical Fiction'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM books WHERE isbn = '9798275086690');
INSERT INTO books (title, author, year, isbn, description, cover_image, url, web_url, language, category)
  SELECT 'Pulse Of The Body: A Novel of Medicine, Humanity, and the Edge of Life (Hardcover)', 'Walter Kyo Csoelle', 2025, '9798275098167', 'Hardcover - November 18, 2025 by Walter Kyo Csoelle. Independently published, 212 pages, ISBN-13 979-8275098167 (ASIN B0G2XC7PZ8). The novel follows Thomas Shimur, a former biology teacher with terminal kidney failure, as he enters a nephrology ward and confronts fear, grief, identity loss, and acceptance. Dr. Lea Mountchain, burdened by unresolved clinical trauma, and Prof. Victor Kraal, a visionary but ethically conflicted renal surgeon, become central to his journey. Across dialysis rooms, surgical theaters, ICU corridors, and family confrontations, the story explores dependence, dignity, informed choice, and the limits of intervention. Pulse of the Body portrays nephrology as a microcosm of human life where technology, ethics, love, guilt, hope, and grief intersect.', 'https://m.media-amazon.com/images/I/613ow76gD3L._SY466_.jpg', 'https://www.amazon.com/dp/B0G2XC7PZ8', 'https://www.amazon.com/stores/author/B0G2TCCJZZ', 'English', 'Medical Fiction'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM books WHERE isbn = '9798275098167');

COMMIT;

-- Verification (expect 26 rows, four Kindle records with corrected titles/years, six new ISBN-13 rows):
-- SELECT id, year, isbn, title FROM books ORDER BY id;
